version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    pre_build:
      - sphinx-apidoc --implicit-namespaces -o overlay-language/docs/api overlay-language/src/overlay

sphinx:
  configuration: overlay-language/docs/conf.py

python:
  install:
    - method: pip
      path: overlay-language
      extra_requirements:
        - docs
