version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"

sphinx:
  configuration: packages/mixinv2/docs/conf.py

python:
  install:
    - method: pip
      path: packages/mixinv2
      extra_requirements:
        - docs
